version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Zinebzineb27"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: